/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as AssetsMyAssetsIndexRouteImport } from './routes/assets/my-assets/index'
import { Route as AssetsMyAssetsIdRouteImport } from './routes/assets/my-assets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsMyAssetsIndexRoute = AssetsMyAssetsIndexRouteImport.update({
  id: '/assets/my-assets/',
  path: '/assets/my-assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsMyAssetsIdRoute = AssetsMyAssetsIdRouteImport.update({
  id: '/assets/my-assets/$id',
  path: '/assets/my-assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets': typeof AssetsMyAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets': typeof AssetsMyAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets/': typeof AssetsMyAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maintenance'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/assets/my-assets/$id'
    | '/assets/my-assets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maintenance'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/assets/my-assets/$id'
    | '/assets/my-assets'
  id:
    | '__root__'
    | '/'
    | '/maintenance/'
    | '/sign-in/'
    | '/sign-up/'
    | '/verify-email/'
    | '/assets/my-assets/$id'
    | '/assets/my-assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
  AssetsMyAssetsIdRoute: typeof AssetsMyAssetsIdRoute
  AssetsMyAssetsIndexRoute: typeof AssetsMyAssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/my-assets/': {
      id: '/assets/my-assets/'
      path: '/assets/my-assets'
      fullPath: '/assets/my-assets'
      preLoaderRoute: typeof AssetsMyAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/my-assets/$id': {
      id: '/assets/my-assets/$id'
      path: '/assets/my-assets/$id'
      fullPath: '/assets/my-assets/$id'
      preLoaderRoute: typeof AssetsMyAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
  AssetsMyAssetsIdRoute: AssetsMyAssetsIdRoute,
  AssetsMyAssetsIndexRoute: AssetsMyAssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
