/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeIndex2RouteImport } from './routes/home/index 2'
import { Route as AssetsMyAssetsIndexRouteImport } from './routes/assets/my-assets/index'
import { Route as AssetsMyAssetsIdRouteImport } from './routes/assets/my-assets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndex2Route = HomeIndex2RouteImport.update({
  id: '/home/index 2',
  path: '/home/index 2',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsMyAssetsIndexRoute = AssetsMyAssetsIndexRouteImport.update({
  id: '/assets/my-assets/',
  path: '/assets/my-assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsMyAssetsIdRoute = AssetsMyAssetsIdRouteImport.update({
  id: '/assets/my-assets/$id',
  path: '/assets/my-assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/index 2': typeof HomeIndex2Route
  '/home': typeof HomeIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets': typeof AssetsMyAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/index 2': typeof HomeIndex2Route
  '/home': typeof HomeIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets': typeof AssetsMyAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/index 2': typeof HomeIndex2Route
  '/home/': typeof HomeIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/assets/my-assets/$id': typeof AssetsMyAssetsIdRoute
  '/assets/my-assets/': typeof AssetsMyAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/index 2'
    | '/home'
    | '/maintenance'
    | '/sign-in'
    | '/sign-up'
    | '/assets/my-assets/$id'
    | '/assets/my-assets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/index 2'
    | '/home'
    | '/maintenance'
    | '/sign-in'
    | '/sign-up'
    | '/assets/my-assets/$id'
    | '/assets/my-assets'
  id:
    | '__root__'
    | '/'
    | '/home/index 2'
    | '/home/'
    | '/maintenance/'
    | '/sign-in/'
    | '/sign-up/'
    | '/assets/my-assets/$id'
    | '/assets/my-assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeIndex2Route: typeof HomeIndex2Route
  HomeIndexRoute: typeof HomeIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  AssetsMyAssetsIdRoute: typeof AssetsMyAssetsIdRoute
  AssetsMyAssetsIndexRoute: typeof AssetsMyAssetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/index 2': {
      id: '/home/index 2'
      path: '/home/index 2'
      fullPath: '/home/index 2'
      preLoaderRoute: typeof HomeIndex2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/my-assets/': {
      id: '/assets/my-assets/'
      path: '/assets/my-assets'
      fullPath: '/assets/my-assets'
      preLoaderRoute: typeof AssetsMyAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/my-assets/$id': {
      id: '/assets/my-assets/$id'
      path: '/assets/my-assets/$id'
      fullPath: '/assets/my-assets/$id'
      preLoaderRoute: typeof AssetsMyAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeIndex2Route: HomeIndex2Route,
  HomeIndexRoute: HomeIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  AssetsMyAssetsIdRoute: AssetsMyAssetsIdRoute,
  AssetsMyAssetsIndexRoute: AssetsMyAssetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
